- name: Create user Groups
  ansible.builtin.group:
    name: "{{ new_group.key }}"
    gid: "{{ new_group.value }}"
    state: present
  loop: "{{ new_group | dict2items }}"
  loop_control:
    loop_var: new_group