- name: Install httpd
  dnf:
    name: httpd
    state: present

- name: Back up the httpd.conf file
  copy:
    src: /etc/httpd/conf/httpd.conf
    dest: /etc/httpd/conf/httpd.conf.org
    remote_src: true