- name: Basic setting of OS
  hosts: redmine
  become: true

  roles:
    - vim
    - curl
    - unzip
    - ssm
    - awscli
    - dnf-automatic
    - locale_timezone
    - wget
    - hosts
    - dns
    - apache