user_list:
  - user_name: itensys
    group_id: 1001
  
  - user_name: itensys_test
    group_id: 1003

  - user_name: acctngsys
    group_id: 1002

  - user_name: acctngsys_test
    group_id: 1004

  - user_name: asteria_edisys
    group_id: 1009

  - user_name: asteria_edisys_test 
    group_id: 1010

  - user_name: skymartuser 
    group_id: 1009

  - user_name: skymartuser_test
    group_id: 1010

