- name: User control
  user:
    name: "{{ users.name }}"
    state: "{{ users.state }}"
  loop: "{{ target_users }}"
  loop_control:
    loop_var: users

- name: Change group gid
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state }}"
  loop: "{{ target_group }}"
