- name: Install vim
  dnf:
    name: vim
    state: present

- name: Backup vimrc file
  copy:
    src: /etc/vimrc
    dest: /etc/vimrc.org
    owner: root
    group: root
    mode: "0644"

- name: Add custom vimrc include line
  lineinfile:
    path: /etc/vimrc
    line: 'source /etc/vimrc.d/higashi21.vim'
    state: present

- name: Custom vim configuration
  template:
    src: higashi21vimrc.j2
    dest: /etc/vimrc.d/higashi21.vim
    owner: root
    group: root
    mode: "0644"
