new_group:
  itensys: 1001
  acctngsys: 1002
  itensys_test: 1003
  acctngsys_test: 1004
  asteria_edisys: 1005
  asteria_edisys_test: 1006
  skymartuser: 1007
  skymartuser_test: 1008
  asteria_edi: 1009
  asteria_edi_test: 1010