- name: Basic setting of OS
  hosts: redmine
  become: true

  roles:
    - vim
    - curl
    - unzip
    - dnf-automatic
    - nginx
    - locale_timezone
    - wget
    - hosts
    - dns
    - swap
    - apache