- name: Ensure chmod directory exists
  file:
    path: "{{ chmod_direc }}{{ item.dir_name }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ item.gid }}"
    mode: '0770'
    recurse: yes
  loop: "{{ target_dir }}"

