- name: Confirm user exists
  user:
    name: "{{ item.user}}"
    state: present
    createhome: no
    system: yes
  loop: "{{ cron_jobs }}"
  when: item.user != "root"
  run_once: true

- name: Configure crontab
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    month: "{{ item.month }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.job }}"
    state: present
  loop: "{{ cron_jobs }}"